version: '3.2'

services:
  mongodb: 
    build: .
    # image: mong
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      # - mongodb:/data/db
      - type: "volume"
        source: "mongodb_mongodb_data"
        target: "/data/db0"
      - type: "volume"
        source: "mongodb_mongodb0_logs"
        target: "/var/log/mongodb/"
    networks: 
      - mongo_net
volumes:
  mongodb_mongodb_data:
    external: true
  mongodb_mongodb0_logs:
    external: true
networks: 
  mongo_net:
    driver: bridge