version: '3.2'

services:
  mongodb: 
    build: .
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - type: "volume"
        source: "mongodb_data"
        target: "/data/db0"
      - type: "volume"
        source: "mongodb0_logs"
        target: "/var/log/mongodb/"
    networks: 
      - mongo_net
volumes:
  mongodb_data:
  mongodb0_logs:
networks: 
  mongo_net:
    driver: bridge