version: '3.2'

services:
  mongodb: 
    build: .
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      # - mongodb:/data/db
      - type: "volume"
        source: "data"
        target: "/data/db"
      - type: "volume"
        source: "logs"
        target: "/var/log/mongodb/"
    networks: 
      - mongo_net
volumes:
  data:
  logs:
networks: 
  mongo_net:
