version: '3.2'

services:
  mongodb: 
    build: .
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - type: "volume"
        source: "mongodb0"
        target: "/data/db"
      - type: "volume"
        source: "mongodb0_logs"
        target: "/var/log/mongodb/"
volumes:
  mongodb0:
  mongodb0_logs: