version: '2'

services:
  mongodb0: 
    build: ./mongodb0
    # image: mongodb_mongodb
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - "data0:/data/db"
      - "logs0:/var/log/mongodb/"
    networks: 
      - mongo_net

  mongodb1: 
    build: ./mongodb1
    # image: mongodb_mongodb
    container_name: "mongodb1"
    ports:
      - "27018:27017"
    volumes:
      - "data1:/data/db"
      - "logs1:/var/log/mongodb/"
    networks: 
      - mongo_net
  mongodb2: 
    build: ./mongodb0
    # image: mongodb_mongodb
    container_name: "mongodb2"
    ports:
      - "27019:27017"
    volumes:
      - "data2:/data/db"
      - "logs2:/var/log/mongodb/"
    networks: 
      - mongo_net
volumes:
  data0:
  logs0:
  data1:
  logs1:
  data2:
  logs2:
networks: 
  mongo_net:
    driver: bridge