version: '2'

services: 
  mongodb0:
    build: ./mongodb0/
    container_name: "mongodb-master"
    ports:
      - "27017:27017"
    volumes:
      - /mongodb0:/data/db
    networks: 
      - mongodb_net
  
#   mongodb1:
#     build: ./mongodb1/
#     container_name: "mongodb-slave"
#     ports:
#       - "27018:27018"
#     volumes:
#       - /mongodb1:/data/db
#     networks: 
#       - mongodb_net
networks: 
  mongodb_net: