version: '3.2'

services:
  mongodb0: 
    build: ./mongodb0
    # image: mongodb_mongodb
    container_name: "mongodb"
    ports:
      - "27017:27017"
    volumes:
      - type: "volume"
        source: "data0"
        target: "/data/db"
      - type: "volume"
        source: "logs0"
        target: "/var/log/mongodb/"
    networks: 
      - mongo_net

  mongodb1: 
    build: ./mongodb1
    # image: mongodb_mongodb
    container_name: "mongodb1"
    ports:
      - "27018:27017"
    volumes:
      - type: "volume"
        source: "data1"
        target: "/data/db"
      - type: "volume"
        source: "logs1"
        target: "/var/log/mongodb/"
    networks: 
      - mongo_net
  mongodb2: 
    build: ./mongodb0
    # image: mongodb_mongodb
    container_name: "mongodb2"
    ports:
      - "27019:27017"
    volumes:
      - type: "volume"
        source: "data2"
        target: "/data/db"
      - type: "volume"
        source: "logs2"
        target: "/var/log/mongodb/"
    networks: 
      - mongo_net
volumes:
  data0:
  logs0:
  data1:
  logs1:
  data2:
  logs2:
networks: 
  mongo_net:
    driver: bridge